cpu-boost: Adapt kthread workqueue for 4.9
After commit 87a610a3637b771d7a1ce8f20895584a3c88b176, some of kthread workqueue that was picked
from 3.18 are get problem with implicit declaration of some function.

Current solution for now, is following and adapt function name to symlink with this 4.9 changes.

Changed code:
* queue_kthread_work -> kthread_queue_work
* init_kthread_worker -> kthread_init_worker
* init_kthread_work -> kthread_init_work

Compilation issue:
./drivers/cpufreq/cpu-boost.c:251:2: error: implicit declaration of function 'queue_kthread_work' [-Werror,-Wimplicit-function-declaration]
        queue_kthread_work(&cpu_boost_worker, &input_boost_work);
        ^
../drivers/cpufreq/cpu-boost.c:332:2: error: implicit declaration of function 'init_kthread_worker' [-Werror,-Wimplicit-function-declaration]
        init_kthread_worker(&cpu_boost_worker);
        ^
../drivers/cpufreq/cpu-boost.c:340:2: error: implicit declaration of function 'init_kthread_work' [-Werror,-Wimplicit-function-declaration]
        init_kthread_work(&input_boost_work, do_input_boost);
        ^
../drivers/cpufreq/cpu-boost.c:340:2: note: did you mean 'init_kthread_worker'?
../drivers/cpufreq/cpu-boost.c:332:2: note: 'init_kthread_worker' declared here
        init_kthread_worker(&cpu_boost_worker);
        ^
3 errors generated.

Signed-off-by: Dicky Herlambang <herlambangdicky5@gmail.com>
Signed-off-by: prorooter007 <shreyashwasnik112@gmail.com>